let music=[
    {
        name:"出山",
        geshou:"王胜男",
        shichang:"3:38",
        icon1:"/assets/img/redu.png",
        icon2:"/assets/img/bofang.png",
        icon3:"/assets/img/diange.png",
        xian:"——————————————————————————————————————————"
    },
    {
        name:"往后余生",
        geshou:"马良",
        shichang:"3:58",
        icon1:"/assets/img/redu.png",
        icon2:"/assets/img/bofang.png",
        icon3:"/assets/img/diange.png",
        xian:"——————————————————————————————————————————"
    },
    {
        name:"沙漠骆驼",
        geshou:"展展与罗罗",
        shichang:"5:38",
        icon1:"/assets/img/redu.png",
        icon2:"/assets/img/bofang.png",
        icon3:"/assets/img/diange.png",
        xian:"——————————————————————————————————————————"
    },
    {
        name:"沙漠骆驼",
        geshou:"展展与罗罗",
        shichang:"5:38",
        icon1:"/assets/img/redu.png",
        icon2:"/assets/img/bofang.png",
        icon3:"/assets/img/diange.png",
        xian:"——————————————————————————————————————————"
    },
    {
        name:"乞丐",
        geshou:"摩登兄弟",
        shichang:"4:07",
        icon1:"/assets/img/redu.png",
        icon2:"/assets/img/bofang.png",
        icon3:"/assets/img/diange.png",
        xian:"——————————————————————————————————————————"
    },
    {
        name:"乞丐",
        geshou:"摩登兄弟",
        shichang:"4:07",
        icon1:"/assets/img/redu.png",
        icon2:"/assets/img/bofang.png",
        icon3:"/assets/img/diange.png",
        xian:"——————————————————————————————————————————"
    },
    {
        name:"学猫叫",
        geshou:"冯提莫",
        shichang:"3:15",
        icon1:"/assets/img/redu.png",
        icon2:"/assets/img/bofang.png",
        icon3:"/assets/img/diange.png",
        xian:"——————————————————————————————————————————"
    },
    {
        name:"学猫叫",
        geshou:"冯提莫",
        shichang:"3:15",
        icon1:"/assets/img/redu.png",
            icon2:"/assets/img/bofang.png",
        icon3:"/assets/img/diange.png",
        xian:"——————————————————————————————————————————"

    },
    {
        name:"学猫叫",
        geshou:"冯提莫",
        shichang:"3:15",
        icon1:"/assets/img/redu.png",
        icon2:"/assets/img/bofang.png",
        icon3:"/assets/img/diange.png",
        xian:"——————————————————————————————————————————"
    },
    {
        name:"学猫叫",
        geshou:"冯提莫",
        shichang:"3:15",
        icon1:"/assets/img/redu"+".png",
        icon2:"/assets/img/bofang.png",
        icon3:"/assets/img/diange.png",
        xian:"——————————————————————————————————————————"
    },
        {
        name:"出山",
        geshou:"王胜男",
        shichang:"3:38",
        icon1:"/assets/img/redu.png",
        icon2:"/assets/img/bofang.png",
        icon3:"/assets/img/diange.png",
        xian:"——————————————————————————————————————————"
    },
    {
        name:"往后余生",
        geshou:"马良",
        shichang:"3:58",
        icon1:"/assets/img/redu.png",
        icon2:"/assets/img/bofang.png",
        icon3:"/assets/img/diange.png",
        xian:"——————————————————————————————————————————"
    },
    {
        name:"沙漠骆驼",
        geshou:"展展与罗罗",
        shichang:"5:38",
        icon1:"/assets/img/redu.png",
        icon2:"/assets/img/bofang.png",
        icon3:"/assets/img/diange.png",
        xian:"——————————————————————————————————————————"
    },
    {
        name:"沙漠骆驼",
        geshou:"展展与罗罗",
        shichang:"5:38",
        icon1:"/assets/img/redu.png",
        icon2:"/assets/img/bofang.png",
        icon3:"/assets/img/diange.png",
        xian:"——————————————————————————————————————————"
    },
    {
        name:"乞丐",
        geshou:"摩登兄弟",
        shichang:"4:07",
        icon1:"/assets/img/redu.png",
        icon2:"/assets/img/bofang.png",
        icon3:"/assets/img/diange.png",
        xian:"——————————————————————————————————————————"
    },
    {
        name:"乞丐",
        geshou:"摩登兄弟",
        shichang:"4:07",
        icon1:"/assets/img/redu.png",
        icon2:"/assets/img/bofang.png",
        icon3:"/assets/img/diange.png",
        xian:"——————————————————————————————————————————"
    },
    {
        name:"学猫叫",
        geshou:"冯提莫",
        shichang:"3:15",
        icon1:"/assets/img/redu.png",
        icon2:"/assets/img/bofang.png",
        icon3:"/assets/img/diange.png",
        xian:"——————————————————————————————————————————"
    },
    {
        name:"学猫叫",
        geshou:"冯提莫",
        shichang:"3:15",
        icon1:"/assets/img/redu.png",
            icon2:"/assets/img/bofang.png",
        icon3:"/assets/img/diange.png",
        xian:"——————————————————————————————————————————"

    },
    {
        name:"学猫叫",
        geshou:"冯提莫",
        shichang:"3:15",
        icon1:"/assets/img/redu.png",
        icon2:"/assets/img/bofang.png",
        icon3:"/assets/img/diange.png",
        xian:"——————————————————————————————————————————"
    },
    {
        name:"学猫叫",
        geshou:"冯提莫",
        shichang:"3:15",
        icon1:"/assets/img/redu"+".png",
        icon2:"/assets/img/bofang.png",
        icon3:"/assets/img/diange.png",
        xian:"——————————————————————————————————————————"
    }
];

export default {
    music
}