let teach = {
    "001":{
        "凌峰楼A座":[
            [
                {
                    state:true
                },
                {
                    state:true
                },
                {
                    state:true
                },
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:false
                }
            ],
            [
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:false
                }
            ],
            [
                {
                    state:true
                },
                {
                    state:true
                },
                {
                    state:true
                },
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                }
            ],
            [
                {
                    state:true
                },
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:false
                }
            ],
            [
                {
                    state:true
                },
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                }
            ],
            [
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:false
                }
            ],
        ],
        "凌峰楼B座":[
            [
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                }
            ],
            [
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                }
            ],
            [
                {
                    state:true
                },
                {
                    state:true
                },
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                }
            ],
            [
                {
                    state:true
                },
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:false
                }
            ],
            [
                {
                    state:true
                },
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:false
                }
            ],
            [
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:false
                }
            ],
        ],       
        "凌峰楼C座":[
            [
                {
                    state:true
                },
                {
                    state:true
                },
                {
                    state:true
                },
                {
                    state:true
                },
                {
                    state:true
                },
                {
                    state:true
                },
                {
                    state:false
                }
            ],
            [
                {
                    state:true
                },
                {
                    state:true
                },
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:true
                }
            ],
            [
                {
                    state:true
                },
                {
                    state:true
                },
                {
                    state:true
                },
                {
                    state:true
                },
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:false
                }
            ],
            [
                {
                    state:true
                },
                {
                    state:true
                },
                {
                    state:true
                },
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:true
                }
            ],
            [
                {
                    state:true
                },
                {
                    state:true
                },
                {
                    state:true
                },
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:false
                }
            ],
            [
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:true
                },
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:false
                }
            ],
        ]
    },
    "002":{
        "楼二A座":[
            [
                {
                    state:true
                },
                {
                    state:true
                },
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:false
                }
            ],
            [
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                }
            ],
            [
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                }
            ],
            [
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:false
                }
            ],
            [
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                }
            ],
            [
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:false
                }
            ],
        ],
        "楼二B座":[
            [
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                }
            ],
            [
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                }
            ],
            [
                {
                    state:true
                },
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                }
            ],
            [
                {
                    state:true
                },
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:false
                }
            ],
            [
                {
                    state:true
                },
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:false
                }
            ],
            [
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                }
            ],
        ]
    },
    "003":{
        "楼三A座":[
            [
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:false
                }
            ],
            [
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                }
            ],
            [
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                }
            ],
            [
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                }
            ],
            [
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                }
            ],
            [
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:false
                }
            ],
        ],
        "楼三B座":[
            [
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                }
            ],
            [
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                }
            ],
            [
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                }
            ],
            [
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                }
            ],
            [
                {
                    state:true
                },
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                }
            ],
            [
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                }
            ],
        ]
    },
    "004":{
        "楼三A座":[
            [
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:false
                }
            ],
            [
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                }
            ],
            [
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                }
            ],
            [
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                }
            ],
            [
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                }
            ],
            [
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:false
                }
            ],
        ],
        "楼三B座":[
            [
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                }
            ],
            [
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                }
            ],
            [
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                }
            ],
            [
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                }
            ],
            [
                {
                    state:true
                },
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                }
            ],
            [
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                }
            ],
        ]
    },
    "005":{
        "楼五A座":[
            [
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                }
            ],
            [
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                }
            ],
            [
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                }
            ],
            [
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:false
                }
            ],
            [
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                }
            ],
            [
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                }
            ],
        ],
        "楼五B座":[
            [
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                }
            ],
            [
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                }
            ],
            [
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                }
            ],
            [
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:false
                }
            ],
            [
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:false
                }
            ],
            [
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:false
                },
                {
                    state:true
                },
                {
                    state:false
                }
            ],
        ]
    },
    




}


export default {
    teach
};