let teach = {
    "001":{
        "凌峰楼A座":[
            [true,true,true,true,false,true,false,false,false,false,false,false],
            [false,true,true,false,false,true,false,false,false,false,false,false],
            [true,true,true,true,false,true,false,false,false,false,false,false],
            [true,true,true,true,false,true,false,false,false,false,false,false],
            [true,true,true,true,false,true,false,false,false,false,false,false],
            [true,true,true,true,false,true,false,false,false,false,false,false]
        ],
        "凌峰楼B座":[
            [true,false,true,true,false,false,false],
            [false,false,true,false,false,false,false],
            [true,true,true,false,false,false,false],
            [true,true,false,false,false,true,false],
            [true,true,false,true,false,true,false],
            [false,true,false,true,false,true,false]
        ],
        "凌峰楼C座":[
            [true,true,true,true,true,true,false],
            [true,true,true,false,false,true,true],
            [true,true,true,true,true,false,false],
            [true,true,true,true,false,true,true],
            [true,true,true,true,false,true,false],
            [false,true,true,true,false,true,false]
        ]
    },
    "002":{
        "凌曦楼A座":[
            [true,true,true,false,false,true,false],
            [false,true,false,false,false,false,false],
            [true,false,true,false,false,false,false],
            [false,true,false,true,false,true,false],
            [true,false,false,true,false,false,false],
            [false,false,false,false,false,true,false]
        ],
        "凌曦楼B座":[
            [true,false,false,true,false,false,false],
            [false,false,true,false,false,false,false],
            [true,true,false,false,false,false,false],
            [true,true,false,false,false,true,false],
            [true,true,false,false,false,true,false],
            [false,true,false,true,false,false,false]
        ]
    },
    "003":{
        "凌波楼A座":[
            [false,true,true,false,false,true,false],
            [false,false,false,false,false,false,false],
            [false,false,true,false,false,false,false],
            [false,false,false,true,false,false,false],
            [true,false,false,false,false,false,false],
            [false,false,false,false,false,true,false]
        ],
        "凌波楼B座":[[false,false,false,true,false,false,false],
            [false,false,true,false,false,false,false],
            [true,false,false,false,false,false,false],
            [true,false,false,false,false,false,false],
            [true,true,false,false,false,false,false],
            [false,false,false,true,false,false,false]
        ]
    },
    "004":{
        "逸云楼A座":[
            [false,true,true,false,false,true,false],
            [false,false,false,false,false,false,false],
            [false,false,true,false,false,false,false],
            [false,false,false,true,false,false,false],
            [true,false,false,false,false,false,false],
            [false,false,false,false,false,true,false]
        ],
        "逸云楼B座":[
            [false,false,false,true,false,false,false],
            [false,false,true,false,false,false,false],
            [true,false,false,false,false,false,false],
            [true,false,false,false,false,false,false],
            [true,true,false,false,false,false,false],
            [false,false,false,true,false,false,false]
        ]
    },
    "005":{
        "逸思楼A座":[
            [true,false,true,false,false,false,false],
            [false,false,false,false,false,false,false],
            [true,false,false,false,false,false,false],
            [false,true,false,false,false,true,false],
            [true,false,false,false,false,false,false],
            [false,false,false,false,false,false,false]
        ],
        "逸思楼B座":[
            [false,false,false,false,false,false,false],
            [false,false,false,false,false,false,false],
            [false,true,false,false,false,false,false],
            [false,true,false,false,false,true,false],
            [false,true,false,false,false,true,false],
            [false,true,false,false,false,true,false]
        ]
    },
    "006":{
        "机电大楼A座":[
            [true,false,true,false,false,false,false],
            [false,false,false,false,false,false,false],
            [true,false,false,false,false,false,false],
            [false,true,false,false,false,true,false],
            [true,false,false,false,false,false,false],
            [false,false,false,false,false,false,false]
        ],
        "机电大楼B座":[
            [false,false,false,false,false,false,false],
            [false,false,false,false,false,false,false],
            [false,true,false,false,false,false,false],
            [false,true,false,false,false,true,false],
            [false,true,false,false,false,true,false],
            [false,true,false,false,false,true,false]
        ]
    }
}

export default {
    teach
};